version: '3.1'

networks:
  netflow_network:
    driver: bridge
services:
  db:
    image: postgres
    networks:
      netflow_network:
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: netflow
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 5442:5432
  anyconnectusesapi:
    image: ciscoliveru/anyconnectusersapi:latest
    networks:
      netflow_network:
    restart: always
    environment:
      PSQLIP: db
      PSQLPORT: 5432
      PSQLUSER: netflow
      PSQLPASSWORD: netflow
      DEBUGMODE: 0
      PSQLDBNAME: netflow
      TABLENAME: anyconnect
    ports:
      - 8182:8181
  anyconnectuses:
    image: ciscoliveru/anyconnectusers:latest
    depends_on:
      - db
    networks:
      netflow_network:
    restart: always
    environment:
      PSQLIP: db
      PSQLPORT: 5432
      PSQLUSER: netflow
      PSQLPASSWORD: netflow
      DEBUGMODE: 0
      PSQLDBNAME: netflow
      TABLENAME: anyconnect
    ports:
      - 7002:7002
  syslogcollectorv2:
    image: ciscoliveru/syslogcollectorv2:latest
    depends_on:
      - db
    networks:
      netflow_network:
    restart: always
    environment:
      TZ: Europe/Moscow
      PSQLIP: db
      PSQLMODE: 1
      PSQLPORT: 5432
      PSQLUSER: netflow
      PSQLPASSWORD: netflow
      DEBUGMODE: 0
      PSQLDBNAME: netflow
    ports:
      - 514:514/udp
  syslogapiv2:
    image: ciscoliveru/syslogapiv2:latest
    depends_on:
      - db
    networks:
      netflow_network:
    restart: always
    environment:
      TZ: Europe/Moscow
      PSQLIP: db
      PSQLMODE: 1
      PSQLPORT: 5432
      PSQLUSER: netflow
      PSQLPASSWORD: netflow
      DEBUGMODE: 0
      PSQLDBNAME: netflow
    ports:
      - 8181:80